export const metadata = {
  title: 'Dropdown Challange',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="pt-BR">
      <body>{children}</body>
    </html>
  )
}
